web:
  build: .
  restart: always
  command: python -u app.py
  ports:
    - "80:5000"
  volumes:
    - .:/app
  links:
    - mongo
  environment: 
    PYTHONUNBUFFERED: 1
    PASSWORD: example
mongo:
  image: mongo:3.6.1
  restart: always
mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    links:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example

mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
    restart: always

mqtt:
  build: ./mqtt
  restart: always
  command: python -u main.py
  volumes:
    - ./mqtt:/app
  links:
    - mongo
    - mosquitto
  environment: 
    PYTHONUNBUFFERED: 1


